-- Ej6
-- Daniel Izquierdo Bonilla
CREATE TABLE REGISTRO
(
    NOMBRE      VARCHAR2(100),
    APELLIDO    VARCHAR2(100),
    TIPO_CAMBIO VARCHAR2(100),
    ANTIGUO     VARCHAR2(100),
    NUEVO       VARCHAR2(100)
);

CREATE OR REPLACE TRIGGER CONTROL_CAMBIOS
    BEFORE UPDATE OR INSERT OR DELETE
    ON EMPLOYEES
    FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO REGISTRO (NOMBRE, APELLIDO, TIPO_CAMBIO) VALUES (:new.FIRST_NAME, :new.LAST_NAME, 'Alta empleado');
    ELSIF UPDATING ('SALARY') THEN
        INSERT INTO REGISTRO VALUES (:new.FIRST_NAME, :new.LAST_NAME, 'Cambio salario', :old.SALARY, :new.SALARY);
    ELSIF UPDATING ('EMAIL') THEN
        INSERT INTO REGISTRO
        VALUES (:new.FIRST_NAME, :new.LAST_NAME, 'Cambio email', :old.EMAIL, :new.EMAIL);
    ELSIF DELETING THEN
        INSERT INTO REGISTRO (NOMBRE, APELLIDO, TIPO_CAMBIO) VALUES (:old.FIRST_NAME, :old.LAST_NAME, 'Baja empleado');
    END IF;
END;