USE hollywood;

-- Borrar tablas

DROP TABLE IF EXISTS ACTUAN;
DROP TABLE IF EXISTS CASADOS;
DROP TABLE IF EXISTS PELICULAS;
DROP TABLE IF EXISTS DIRECTORES;
DROP TABLE IF EXISTS ACTORES;

-- Crear tablas

CREATE TABLE PELICULAS(
    nombre VARCHAR(50) PRIMARY KEY,
    ano YEAR NOT NULL,
    nacion VARCHAR(25) NOT NULL,
    calif FLOAT(1) NOT NULL,
    nom_prot VARCHAR (50) NOT NULL,
    nom_dir VARCHAR (50) NOT NULL);

CREATE TABLE ACTORES(
    nombre VARCHAR(50) PRIMARY KEY,
    sexo VARCHAR(1) CHECK(sexo='F' OR sexo='M') NOT NULL,
    fecha_nac DATE NOT NULL,
    nacion VARCHAR(25) NOT NULL);

CREATE TABLE DIRECTORES(
    nombre VARCHAR(50) PRIMARY KEY,
    sexo VARCHAR(1) CHECK(sexo='F' OR sexo='M') NOT NULL,
    fecha_nac DATE NOT NULL,
    nacion VARCHAR(25) NOT NULL);

CREATE TABLE CASADOS(
    nom1 VARCHAR(50) NOT NULL,
    nom2 VARCHAR(50) NOT NULL,
    PRIMARY KEY(nom1));

CREATE TABLE ACTUAN(
    nom_actor VARCHAR(50) NOT NULL,
    nom_peli VARCHAR(50) NOT NULL,
    PRIMARY KEY(nom_actor,nom_peli));

-- Crear FKs

ALTER TABLE CASADOS ADD FOREIGN KEY (nom1) REFERENCES ACTORES(nombre);
ALTER TABLE CASADOS ADD FOREIGN KEY (nom2) REFERENCES ACTORES(nombre);
ALTER TABLE PELICULAS ADD FOREIGN KEY (nom_dir) REFERENCES DIRECTORES(nombre);
ALTER TABLE PELICULAS ADD FOREIGN KEY (nom_prot) REFERENCES ACTORES(nombre);
ALTER TABLE ACTUAN ADD FOREIGN KEY (nom_peli) REFERENCES PELICULAS(nombre);
ALTER TABLE ACTUAN ADD FOREIGN KEY (nom_actor) REFERENCES ACTORES(nombre);